# Generated by Django 6.0.2 on 2026-03-01 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1)),
                ('proposal_data', models.JSONField(blank=True, null=True)),
                ('underwriting_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('identified_health_profile', models.JSONField(blank=True, null=True)),
                ('decision_rationale', models.TextField(blank=True, null=True)),
                ('waiting_period_details', models.JSONField(blank=True, null=True)),
                ('refer_to_uwr_details', models.JSONField(blank=True, null=True)),
                ('more_questions_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_proposal_data', models.JSONField(blank=True, null=True)),
                ('discrepancy_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='proposal.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ambiguity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiguity_proposal_data', models.JSONField(blank=True, null=True)),
                ('ambiguity_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguities', to='proposal.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
