# Generated by Django 6.0.2 on 2026-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposal_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
