# Generated by Django 5.0.4 on 2026-03-03 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_proposal_response_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uwquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uwquestions', to='proposal.proposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
