"""
Django settings for uwbrain project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k3exq4q5#&(sds!c9nclqc@q)x^(yrq&03u&9y4j2@y09opw&c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['uwbrain-216941414590.asia-south1.run.app', 'localhost', 'https://id-preview--85e59c76-a75b-4d6d-b530-f4518ecb51be.lovable.app', 'https://health-form-flow-216941414590.asia-south1.run.app/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'proposal'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",   # your frontend dev server
    "https://uwbrain-216941414590.asia-south1.run.app",  # your Cloud Run backend
    'https://id-preview--85e59c76-a75b-4d6d-b530-f4518ecb51be.lovable.app',  # your Lovable preview URL
    'https://health-form-flow-216941414590.asia-south1.run.app/'
]
#CORS_ALLOW_ALL_ORIGINS = True

CSRF_COOKIE_HTTPONLY = False  # allow JS to read it
CSRF_TRUSTED_ORIGINS = ["http://localhost:8080"]

ROOT_URLCONF = 'uwbrain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uwbrain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         # tried to create RXPDB7 BUT Created as rxpdb7 (small letters) in deployment
#         'NAME': 'uwbraindb',
#         # may need to change to shreyas [ON LINUX CREATED USER 'shreyas', rest all details same]
#         'USER': 'shreyas',
#         'PASSWORD': 'PHI8888581413',
#         'HOST': 'localhost',
#         "PORT": "5432",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  # Replace with your database name (e.g., 'postgres' or a custom one)
        'USER': 'postgres',  # Replace with your database user (e.g., 'postgres' or a custom one)
        'PASSWORD':'y1H1ZSp:tZ7~7,G"', 
        #os.getenv("DB_PASSWORD"), #os.environ.get('DB_PASSWORD'), # It's best practice to use environment variables for sensitive data
        'HOST': '34.47.227.148',       # Your Cloud SQL instance's Public IP address
        'PORT': '5432',                # Default PostgreSQL port
    }
}
# uwbrain-memory
# y1H1ZSp:tZ7~7,G"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- Your Google Cloud/Gen AI Specific Settings ---

import os
from dotenv import load_dotenv
load_dotenv()
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION")
GOOGLE_GENAI_USE_VERTEXAI = os.getenv("GOOGLE_GENAI_USE_VERTEXAI") == "True"
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")